### ISSUE TITLE
[FALSE POSITIVE[ BED+CHEST

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#241] opened 2022-08-28 21:39 UTC
https://user-images.githubusercontent.com/108226177/187095581-bb1d0a9b-d82d-4257-9d2c-6f2a920fa1a2.mp4

Ncp ver
[00:39:43 INFO]: »Version information«
[00:39:43 INFO]: Server:
[00:39:43 INFO]: git-Paper-1620 ~MC: 1.12.2~
[00:39:43 INFO]: Detected: 1.12.2
[00:39:43 INFO]: NoCheatPlus:
[00:39:43 INFO]: Plugin: 3.17.1-SNAPSHOT-Updated-b148
[00:39:43 INFO]: MCAccess: 1.12-1.12.2 / Spigot-CB-1.12_R1
[00:39:43 INFO]: Features:
[00:39:43 INFO]: blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, BlocksMC1_9, BlocksMC1_10, BlocksMC1_11, BlocksMC1_12
[00:39:43 INFO]: checks: FastConsume, Gutenberg, HotFixFallingBlockPortalEnter, AttackFrequency, FlyingFrequency, KeepAliveFrequency
[00:39:43 INFO]: defaults: pvpKnockBackVelocity
[00:39:43 INFO]: packet-listeners: UseEntityAdapter, MovingFlying, OutgoingPosition, KeepAliveAdapter, SoundDistance, WrongTurnAdapter, Fight
[00:39:43 INFO]: Hooks:
ViolationFrequency~NCP~ 1.0
[00:39:43 INFO]: »Related Plugins«
[00:39:43 INFO]: ProtocolLib v5.0.0-SNAPSHOT-b600, ViaVersion v4.4.2

**Comment by Lysandr0** [comment] 2022-08-30 10:57
Lowjump false positive, duplicate of #239

**Closed as completed by Lysandr0** 2022-08-30 10:57 UTC
Labels: (type) false positive, (resolution) duplicate, (field) moving, legacy MC
