### ISSUE TITLE
End Crystals can be destroyed through walls.

### ISSUE THREAD

**Issue by qumecs** [Updated-NoCheatPlus/NoCheatPlus#285] opened 2023-03-04 13:40 UTC
#### *Complete* output of the `ncp version` command (please prefer text here)
```
[22:31:10 INFO]: »Version information«
[22:31:10 INFO]: Server:
[22:31:10 INFO]: git-Paper-431 ~MC: 1.19.3~
[22:31:10 INFO]: Detected: 1.19.3
[22:31:10 INFO]: NoCheatPlus:
[22:31:10 INFO]: Plugin: 3.17.1-SNAPSHOT-Updated-b154
[22:31:10 INFO]: MCAccess: 1.13-1.19|? / Bukkit-API
[22:31:10 INFO]: Features:
[22:31:10 INFO]: blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, BlocksMC1_9, BlocksMC1_10, BlocksMC1_11, BlocksMC1_12, BlocksMC1_13, BlocksMC1_14, BlocksMC1_15, BlocksMC1_16, BlocksMC1_17, BlocksMC1_19, MCAccessBukkitModern
[22:31:10 INFO]: checks: FastConsume, Gutenberg, HotFixFallingBlockPortalEnter, AttackFrequency, FlyingFrequency, KeepAliveFrequency
[22:31:10 INFO]: defaults: pvpKnockBackVelocity
[22:31:10 INFO]: packet-listeners: UseEntityAdapter, MovingFlying, OutgoingPosition, KeepAliveAdapter, SoundDistance, WrongTurnAdapter, Fight
[22:31:10 INFO]: Hooks:
AllViolations~NCP~ 1.0, ViolationFrequency~NCP~ 1.0
[22:31:10 INFO]: »Related Plugins«
[22:31:10 INFO]: ProtocolLib v5.0.0-SNAPSHOT-b614
```

#### Short description of the issue and how to reproduce (is it random / always happens / side conditions ?)
Unlike other entities, End Crystals can be destroyed through walls. That bug happens all the time.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No. I'm using default config.

#### Do you run any other special plugins that affect game mechanics next to NC+ (skills, machines, adding/changing blocks, other anti-cheating)?
no. I am using only the latest Protocollib and NCP.

**Comment by Lysandr0** [comment] 2023-03-05 07:13
Duplicate of #235 
We don't have a check for hitting entities through walls just yet (something is in the works however).

**Closed as completed by Lysandr0** 2023-03-05 07:13 UTC
Labels: (resolution) duplicate, (field) fight, (type) cheat/bypass/exploit
