### ISSUE TITLE
killaura/aim check

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#293] opened 2023-04-14 12:53 UTC
### Describe the features of this added check
killaura/aura check
### Description of how this check would work
yeah killaura check

**Comment by Lysandr0** [comment] 2023-04-15 20:17
Assuming duplicate of #235 
KillAura checks are not on the highest priority right now. Too much effort for too little gain.

**Closed as completed by Lysandr0** 2023-04-15 20:17 UTC
Labels: (resolution) duplicate, (type) enhancement/feature, (field) fight
