### ISSUE TITLE
Fast break error

### ISSUE THREAD

**Issue by stonar96** [Updated-NoCheatPlus/NoCheatPlus#80] opened 2020-11-10 11:58 UTC
### Full output of /ncp version
```
[12:47:58] [Server thread/INFO]: ---- Version information ----
[12:47:58] [Server thread/INFO]: #### Server ####
[12:47:58] [Server thread/INFO]: git-Paper-261 ~MC: 1.16.4~
[12:47:58] [Server thread/INFO]:   detected: 1.16.4
[12:47:58] [Server thread/INFO]: #### NoCheatPlus ####
[12:47:58] [Server thread/INFO]: Plugin: 3.17-SNAPSHOT-Updated-b83
[12:47:58] [Server thread/INFO]: MCAccess: 1.13-1.16|? / Bukkit-API
[12:47:58] [Server thread/INFO]: Features:
[12:47:58] [Server thread/INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | BlocksMC1_16 | MCAccessBukkitModern
[12:47:58] [Server thread/INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[12:47:58] [Server thread/INFO]:   defaults: pvpKnockBackVelocity
[12:47:58] [Server thread/INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
[12:47:58] [Server thread/INFO]: Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
[12:47:58] [Server thread/INFO]: #### Related Plugins ####
[12:47:58] [Server thread/INFO]: ProtocolLib v4.6.0-SNAPSHOT-b482
```
### Describe the issue
Using fast break, being kicked and rejoining several times produces the following error. Afterwards I can't join anymore.
```
[12:45:23] [Server thread/INFO]: [NC+] stonar96 failed FastBreak: tried to break a block faster than possible (Block: SAND) (VL52)
[12:45:23] [Server thread/INFO]: stonar96 lost connection: (!) Breaking blocks too fast.
[12:45:23] [Craft Scheduler Thread - 3/WARN]: [NoCheatPlus] Failed to execute the command 'ncp kick stonar96 (!) Breaking blocks too fast.': Unhandled exception executing command 'ncp' in plugin NoCheatPlus v3.17-SNAPSHOT-Updated-b83, please check if everything is setup correct. -> log once id=907337162
[12:45:23] [Craft Scheduler Thread - 3/WARN]: [NoCheatPlus] org.bukkit.command.CommandException: Unhandled exception executing command 'ncp' in plugin NoCheatPlus v3.17-SNAPSHOT-Updated-b83
	org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
	org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
	fr.neatmonster.nocheatplus.actions.types.CommandAction.execute(CommandAction.java:62)
	fr.neatmonster.nocheatplus.actions.types.CommandAction.execute(CommandAction.java:33)
	fr.neatmonster.nocheatplus.checks.ViolationData.executeActions(ViolationData.java:197)
	fr.neatmonster.nocheatplus.checks.Check.executeActions(Check.java:168)
	fr.neatmonster.nocheatplus.checks.blockbreak.FastBreak.check(FastBreak.java:113)
	fr.neatmonster.nocheatplus.checks.blockbreak.BlockBreakListener.onBlockBreak(BlockBreakListener.java:191)
	jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:566)
	fr.neatmonster.nocheatplus.event.mini.MultiListenerRegistry$AutoListener.onEvent(MultiListenerRegistry.java:82)
	fr.neatmonster.nocheatplus.event.mini.MiniListenerNode.onEvent(MiniListenerNode.java:157)
	fr.neatmonster.nocheatplus.event.mini.EventRegistryBukkit$4.execute(EventRegistryBukkit.java:124)
	co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
	net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324)
	net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:91)
	net.minecraft.server.v1_16_R3.EntityPlayer.tick(EntityPlayer.java:448)
	net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845)
	net.minecraft.server.v1_16_R3.World.a(World.java:884)
	net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530)
	net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1358)
	net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
	net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211)
	net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999)
	net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
	java.base/java.lang.Thread.run(Thread.java:834)

[12:45:30] [Craft Scheduler Thread - 4/WARN]: [NoCheatPlus] DataMan inconsistencies: missing online players (1) | wrong number of online players (0 instead of 1)
[12:45:40] [Craft Scheduler Thread - 5/WARN]: [NoCheatPlus] DataMan inconsistencies: missing online players (1) | wrong number of online players (0 instead of 1)
[12:45:50] [Craft Scheduler Thread - 6/WARN]: [NoCheatPlus] DataMan inconsistencies: missing online players (1) | wrong number of online players (0 instead of 1)
...
```
### How to reproduce the issue
Setup a fresh (Paper) server, install NCP and ProtocolLib and see above. No other settings or plugins required to reproduce.
### Extra links/Videos (Including debug logs)
None.
### Any possible config options changed or plugins that may cause interference?
No.

**Comment by CaptainObvious0** [comment] 2021-01-11 04:02
Duplicate of #75

**Closed as completed by CaptainObvious0** 2021-01-11 04:02 UTC
