### ISSUE TITLE
BungeeCord notifications?

### ISSUE THREAD

**Issue by lucatolton** [Updated-NoCheatPlus/NoCheatPlus#33] opened 2020-07-08 11:46 UTC
### Describe the features of this added check
BungeeCord notifications, notifications across servers in a bungeecord network
### Description of how this check would work
It should send a notification to each server with the plugin installed

### Any extra information about what should be added? (Config options...)
Being able to specify a server name or have it grab automatically

**Comment by Lysandr0** [comment] 2023-02-25 13:09
Duplicate of #143

**Closed as completed by Lysandr0** 2023-02-25 13:09 UTC
Labels: (resolution) duplicate, (type) enhancement/feature
