### ISSUE TITLE
Placing lillypads on water causes kick for "Invalid block placements"

### ISSUE THREAD

**Issue by MithrandirCraft** [Updated-NoCheatPlus/NoCheatPlus#74] opened 2020-10-24 13:42 UTC
### Full output of /ncp version
```
ncp version
[15:38:19 INFO]: ---- Version information ----
[15:38:19 INFO]: #### Server ####
[15:38:19 INFO]: git-Paper-245 ~MC: 1.16.3~
[15:38:19 INFO]:   detected: 1.16.3
[15:38:19 INFO]: #### NoCheatPlus ####
[15:38:19 INFO]: Plugin: 3.17-SNAPSHOT-Updated-b82
[15:38:19 INFO]: MCAccess: 1.13-1.16|? / Bukkit-API
[15:38:19 INFO]: Features:
[15:38:19 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | BlocksMC1_16 | MCAccessBukkitModern
[15:38:19 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[15:38:19 INFO]:   defaults: pvpKnockBackVelocity
[15:38:19 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
[15:38:19 INFO]: Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
[15:38:19 INFO]: #### Related Plugins ####
[15:38:19 INFO]: ProtocolLib v4.6.0-SNAPSHOT-b481
```
### Describe the issue
Placing lillypads on water causes kick for "Invalid block placements"

### How to reproduce the issue
Place lillypads on water. 

### Any possible config options changed or plugins that may cause interference?
I dobut it, the config is very close to default.

**Comment by CaptainObvious0** [comment] 2021-01-11 04:04
Could you include a debug log in #77 

I'll be marking as closed as its a duplicate of the other issue created.

**Closed as completed by CaptainObvious0** 2021-01-11 04:04 UTC
