### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#247] opened 2022-09-06 15:47 UTC
Build 149, version 1.12.2

https://user-images.githubusercontent.com/108226177/188679190-30f17d0a-d134-4250-8958-c87b8d429902.mp4

**Comment by Lysandr0** [comment] 2022-09-09 18:49
Duplicate of #239

**Closed as completed by Lysandr0** 2022-09-09 18:49 UTC
Labels: (type) false positive, (resolution) duplicate, (field) moving
