### ISSUE TITLE
MLG Water bucketing cuases NoFall trigger.

### ISSUE THREAD

**Issue by BTELNYY** [Updated-NoCheatPlus/NoCheatPlus#174] opened 2021-11-17 00:47 UTC
### Full output of /ncp version
[18:45:51 INFO]: »Version information«
[18:45:51 INFO]: Server:
[18:45:51 INFO]: git-Paper-381 ~MC: 1.17.1~
[18:45:51 INFO]: Detected: 1.17.1
[18:45:51 INFO]: NoCheatPlus:
[18:45:51 INFO]: Plugin: 3.17-SNAPSHOT-Updated-b122
[18:45:51 INFO]: MCAccess: 1.13-1.17|? / Bukkit-API
[18:45:51 INFO]: Features:
[18:45:51 INFO]: blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, BlocksMC1_9, BlocksMC1_10, BlocksMC1_11, BlocksMC1_12, BlocksMC1_13, BlocksMC1_14, BlocksMC1_15, BlocksMC1_16, BlocksMC1_17, MCAccessBukkitModern
[18:45:51 INFO]: checks: FastConsume, Gutenberg, HotFixFallingBlockPortalEnter, AttackFrequency, FlyingFrequency, KeepAliveFrequency
[18:45:51 INFO]: defaults: pvpKnockBackVelocity
[18:45:51 INFO]: packet-listeners: UseEntityAdapter, MovingFlying, OutgoingPosition, KeepAliveAdapter, SoundDistance, WrongTurnAdapter, NoSlow, Fight
[18:45:51 INFO]: Hooks:
AllViolations~NCP~ 1.0, ViolationFrequency~NCP~ 1.0
[18:45:51 INFO]: »Related Plugins«
[18:45:51 INFO]: ProtocolLib v4.7.0

### Describe the issue
Attempting to water MLG causes the server to teleport you back to your jump point and deal damage.

### How to reproduce the issue
Load a paper server with protocol lib, go to a high place deoped, jump off with a water bucket and try to MLG

### Any possible config options changed or plugins that may cause interference?
Default Config.

**Comment by Lysandr0** [comment] 2021-11-21 10:23
Duplicate of #150. Very likely.

**Closed as completed by Lysandr0** 2021-11-21 10:23 UTC
Labels: (resolution) duplicate, (field) moving, (type) bug
