### ISSUE TITLE
Survivalfly: false positive when leaving a waterfall

### ISSUE THREAD

**Issue by Lysandr0** [Updated-NoCheatPlus/NoCheatPlus#3] opened 2020-04-25 06:31 UTC
(Report from Discord)
### Full output of /ncp version
```
[INFO] ---- Version information ----

[INFO] #### Server ####

[INFO] git-Spigot-2040c4c-893ad93 ~MC: 1.15.2~

[INFO] detected: 1.15.2

[INFO] #### NoCheatPlus ####

[INFO] Plugin: 3.17-SNAPSHOT-b1153-CustomFork

[INFO] MCAccess: 1.13.2-1.15|? / Bukkit-API

[INFO] Features:

[INFO] blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | MCAccessBukkitModern

[INFO] checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency

[INFO] defaults: pvpKnockBackVelocity

[INFO] packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight

[INFO] Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0

[INFO] #### Related Plugins ####

[INFO] ProtocolLib v4.5.0 | ProtocolSupport v4.29-dev
```
### Describe the issue
Leaving a waterfall will flag for hSpeed if you leave water and start to fall at a high speed immediately after.
You won't get setbacked for shorter distances/slower falling speeds.

### Extra links/Videos (Including debug logs)
https://www.dropbox.com/s/el2ggvmvx67ipry/leaving_water_fp.mov?dl=0

[Leaving_water_debug.log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/4532460/Leaving_water_debug.log)

   
### Any possible config options changed or plugins that may cause interference?
Default config

**Comment by CaptainObvious0** [comment] 2020-04-26 04:33
Issue caused by rework done for movement out of a liquid, as seen in commit 61cb72. 

This has been fixed in 64bb2bc, but it may require a second look by xaw3ep, since they are the one that made the changes. The changes I made may have interfered with what the check was doing, so I want to make sure the changes I made are correct.

**Closed as completed by CaptainObvious0** 2020-04-26 04:33 UTC
Labels: (type) false positive
