### ISSUE TITLE
Teleportation + fall damage bug

### ISSUE THREAD

**Issue by fuckcuff** [Updated-NoCheatPlus/NoCheatPlus#186] opened 2022-01-01 03:53 UTC
### Full output of /ncp version
![image](https://user-images.githubusercontent.com/67871539/147843573-c6156a96-7c1a-4219-be39-3ce8685062b6.png)
![image](https://user-images.githubusercontent.com/67871539/147843575-b93b2fac-da59-4379-918d-a1dba71493da.png)

### Explanation
teleports players back to the block they fall off of + applies fall damage

### How to reproduce
fall off a block, rotate down to the max and spam right click (can hold any item i believe)

**Comment by Lysandr0** [comment] 2022-01-03 15:16
Duplicate of #150

**Closed as completed by Lysandr0** 2022-01-03 15:16 UTC
Labels: (type) false positive, (resolution) duplicate, (field) moving
