### ISSUE TITLE
empty line on join

### ISSUE THREAD

**Issue by arts7493** [Updated-NoCheatPlus/NoCheatPlus#71] opened 2020-08-28 15:39 UTC
### Full output of /ncp version
[00:38:33] [Server thread/INFO]: ---- Version information ----
[00:38:33] [Server thread/INFO]: #### Server ####
[00:38:33] [Server thread/INFO]: git-Paper-387 ~MC: 1.15.2~
[00:38:33] [Server thread/INFO]: Detected: 1.15.2
[00:38:33] [Server thread/INFO]: #### NoCheatPlus ####
[00:38:33] [Server thread/INFO]: Plugin: 3.17-SNAPSHOT-b6.1.2
[00:38:33] [Server thread/INFO]: MCAccess: 1.13-1.16.2|? / Bukkit-API
[00:38:33] [Server thread/INFO]: Hooks: Citizens2~cncp~ 2.0 | NCPDragDown 1.1 | ViolationFrequency~NCP~ 1.0
[00:38:33] [Server thread/INFO]: #### Related Plugins ####
[00:38:33] [Server thread/INFO]: CompatNoCheatPlus vb90 | ProtocolLib v4.5.1 | ConditionalCommands v1.6 | NCPDragDown v1.0.5
### Describe the issue
show empty line on join
there is no issue on previous version

**Comment by ChiboYen** [comment] 2020-09-03 23:42
Set MOTD to false in the config, then the empty line will go away

**Comment by arts7493** [comment] 2020-09-06 00:46
already, but doesn't work
only player
not op

check please. there is no error previous version

**Comment by ChiboYen** [comment] 2020-09-06 09:26
If the issue is solved for players, then I'd consider it good enough for me, try turning off NCP permission caching but this isn't a real issue

**Comment by MarkElf** [comment] 2020-09-06 14:33
Turning off the motd stopped sending the empty line for me as both op'ed and non-op'ed.

**Comment by CaptainObvious0** [comment] 2021-01-11 04:06
Should be disabled once the configuration value is set to false. Have you restarted the server or tried doing /ncp reload after saving the changes? I'll be marking it as closed for now unless changing the config value doesn't work.

**Closed as completed by CaptainObvious0** 2021-01-11 04:06 UTC
