### ISSUE TITLE
Breaking a Conduit block with pickaxes trigger FastBreak

### ISSUE THREAD

**Issue by molor** [Updated-NoCheatPlus/NoCheatPlus#188] opened 2022-01-12 15:06 UTC
### Full output of /ncp version
```
> ncp version
[18:01:21] »Version information«
[18:01:21] Server:
[18:01:21] git-Paper-141 ~MC: 1.18.1~
[18:01:21] Detected: 1.18.1
[18:01:21] NoCheatPlus:
[18:01:21] Plugin: 3.17-SNAPSHOT-Updated-b127
[18:01:21] MCAccess: 1.13-1.18|? / Bukkit-API
[18:01:21] Features:
[18:01:21] blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, BlocksMC1_9, BlocksMC1_10, BlocksMC1_11, BlocksMC1_12, BlocksMC1_13, BlocksMC1_14, BlocksMC1_15, BlocksMC1_16, BlocksMC1_17, MCAccessBukkitModern
[18:01:21] checks: FastConsume, Gutenberg, HotFixFallingBlockPortalEnter, AttackFrequency, FlyingFrequency, KeepAliveFrequency
[18:01:21] defaults: pvpKnockBackVelocity
[18:01:21] packet-listeners: UseEntityAdapter, MovingFlying, OutgoingPosition, KeepAliveAdapter, SoundDistance, WrongTurnAdapter, NoSlow, Fight
[18:01:21] Hooks:
ViolationFrequency~NCP~ 1.0
[18:01:21] »Related Plugins«
[18:01:21] ProtocolLib v4.8.0-SNAPSHOT-b540
```

### Describe the issue
If normal player breaks a conduit underwater with pickaxe (in my case wooden and diamond tested), then block will not be broken and stays at same location. After few next attempts, player getting kicked with `kickfastbreak`.
### How to reproduce the issue
Break it. I'm not tried to break the conduit in background, but think that there are no difference.

![image](https://user-images.githubusercontent.com/19989717/149165732-d35f618d-f288-4029-a21f-099e2da1adaa.png)

### Any possible config options changed or plugins that may cause interference?
My settings:
```
    fastbreak:
      active: default
      strict: true
      delay: 95
      intervalsurvival: 100
      grace: 2000
      actions: cancel vl>5 cancel log:fastbreak:4:2:i vl>50 cancel log:fastbreak:0:2:if cmdc:kickfastbreak:2:5
```

Currently I added `conduit` to `blocks.allowinstantbreak` to solve this problem temporary, but I hope you will fix it. Thanks!

**Comment by MarkElf** [comment] 2022-01-12 18:33
I would assume this was a mistake with mining times (Blocks 1.13), should be an easy fix:
        // Conduit.
        BlockProperties.setBlockProps("CONDUIT", new BlockProps(BlockProperties.noTool, 3f, BlockProperties.secToMs(4.5)));
to
BlockProperties.setBlockProps(Material.CONDUIT, new BlockProperties.BlockProps(BlockProperties.woodPickaxe, 3.0f, BlockProperties.secToMs(4.5, 2.25, 1.15, 0.75, 0.6, 0.5, 0.4)));

https://minecraft.fandom.com/wiki/Conduit
Edit: wood, not stone

**Comment by Lysandr0** [comment] 2022-01-12 19:16
@MarkElf 
If you did test this, I could push a swift commit :p

**Comment by MarkElf** [comment] 2022-01-13 03:55
Upon testing, I had no issues mining (diamond pick, unenchanted and eff. 4) the conduit with the noTool/original string above ground, underwater, and with aqua affinity.
I mined several conduits under the same conditions with no issues with the changed string.

I was unable to reproduce the issue on localhost 1.17.1.

**Comment by MarkElf** [comment] 2022-01-13 03:56
Upon testing, I had no issues mining (diamond pick, unenchanted and eff. 4) the conduit with the noTool/original string above ground, underwater, and with aqua affinity.
I mined several conduits under the same conditions with no issues with the changed string.

I was unable to reproduce the issue on localhost 1.17.1. My sample size was rather small for testing (3-8) per situation.

**Comment by molor** [comment] 2022-01-13 05:10
Stupid question, but maybe you have bypass (operator/permissions)? Also in my case this happens on Paper 1.18.1

**Comment by MarkElf** [comment] 2022-01-13 17:22
There were no block changes between 1.17.1/1.18.1 (and I'm a bit too lazy to update everything for the localhost test server). It shouldn't really matter as a 1.13 block unless something changed in 1.18.1 that I'm not aware of.
It doesn't appear that I was OP'd during testing and I don't grant myself individual bypass perms, just the notify perm.

**Comment by Lysandr0** [comment] 2022-01-14 11:09
Actually, in 1.18 conduit was assigned to the pickaxe tool, so that may be the reason why the pre-1.18 breaking time is now causing issues.
(Could apply changes in 1.18+ only, but I can't test this right now.

**Comment by Lysandr0** [comment] 2022-01-31 19:13
Conduit is now assigned to the pickaxe only from MC 1.18 and later. (Testing branch)

**Closed as completed by Lysandr0** 2022-01-31 19:13 UTC
Labels: (type) false positive, (field) world, (resolution) fixed
