### ISSUE TITLE
Bug that causes the player to step back while eating and holding down the CTRL (Sprint) button

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#162] opened 2021-09-21 19:01 UTC
I warmly welcome!
One of the players discovered a bug on my server that causes the player to step back while eating and holding down the CTRL (Sprint) button. The bug is quite annoying as players thus get teleported backwards and gain an advantage over the other players during PvP combat

Preview (Link): https://streamable.com/bo3x2h

Information:
NoCheatPlus version: Build 117
Server version: Paper 1.17.1 Build 266
ViaVersion plugin installed to 1.9-1.17.1 support on server, but everyone players on this preview is on 1.17.1

**Comment by Lysandr0** [comment] 2021-09-26 09:48
Actually, now that I watch the video, this looks like a duplicate of #150
Please refer to that for further info/discussion.

**Closed as completed by Lysandr0** 2021-09-26 09:48 UTC
Labels: (type) false positive, (resolution) duplicate, (field) moving
